<?php echo $this->layout()->content; ?>
<!-- carosel -->
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="carousel slide" id="carousel-751368">
        <ol class="carousel-indicators">
          <li data-slide-to="0" data-target="#carousel-751368">
          </li>
          <li data-slide-to="1" data-target="#carousel-751368" class="active">
          </li>
          <li data-slide-to="2" data-target="#carousel-751368">
          </li>
        </ol>
        <div class="carousel-inner">
          <div class="item">
            <img alt="Carousel Bootstrap First" src="<?php echo $this->baseUrl().'/images/1.jpg' ?>" width="500px" heigth="300px"/>
            <div class="carousel-caption">
              <h4>
                First Thumbnail label
              </h4>
              <p>
                Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
              </p>
            </div>
          </div>
          <div class="item active">
            <img alt="Carousel Bootstrap Second" src="<?php echo $this->baseUrl().'/images/1.jpg' ?>" width="500px" heigth="300px"/>
            <div class="carousel-caption">
              <h4>
                Second Thumbnail label
              </h4>
              <p>
                Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
              </p>
            </div>
          </div>
          <div class="item">
            <img alt="Carousel Bootstrap Third" src="<?php echo $this->baseUrl().'/images/1.jpg' ?>" width="500px" heigth="300px"/>
            <div class="carousel-caption">
              <h4>
                Third Thumbnail label
              </h4>
              <p>
                Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
              </p>
            </div>
          </div>
        </div> <a class="left carousel-control" href="#carousel-751368" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a> <a class="right carousel-control" href="#carousel-751368" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
      </div>
    </div>
  </div>
</div>
<!-- Breaks-->
</br> </br> 
<!-- cards -->

  <div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="row">
<?php if($this->index) { 
for($i=0; $i<count($this->index); $i++){
  ?>        
        <div class="col-md-4">
          <div class="thumbnail">
            <img alt="" src="<?php echo $this->baseUrl().'/images/1.jpg' ?>" alt="..." width="500px" heigth="300px" />
            <div class="caption">
              <h3>
                <?php echo $this->index[$i]['course_name'] ?>
              </h3>
              <p>
                <?php echo $this->index[$i]['course_desc'] ?>
              </p>
              <p>
                <a class="btn btn-primary" href="#">Action</a> <a class="btn" href="#">Action</a>
              </p>
            </div>
          </div>
        </div>
<?php } } ?>
      </div>
    </div>
  </div>
</div>

   