<?php echo $this->layout()->content; ?>

<div class="container-fluid">
  <div class="row">
    <div class="jumbotron">
    <h1>Et3lem.com</h1>
    <p>Take the world's best courses, online.</p> 
    </div>
     <center> <h2>Popular Courses</h2> </center>
     <br> <br>
    <?php if($this->index) { 
      for($i=0; $i<count($this->index); $i++){
        ?>        
        <div class="col-md-4">
          <div class="thumbnail">
            <img alt="" src="<?php echo $this->baseUrl().'/images/1.jpg' ?>" alt="..." width="500px" heigth="300px" />
            <div class="caption">
              <h3>
                <?php echo $this->index[$i]['course_name'] ?>
              </h3>
              <p>
                <?php echo $this->index[$i]['course_desc'] ?>
              </p>
              <p>
                <a class="btn btn-primary" href="<?php echo $this->baseUrl().'/course/'.$this->index[$i]['id']; ?>">Action</a>
              </p>
            </div>
          </div>
        </div>
        <?php } } ?>
      </div>
    </div>


