<br /><br />
<div id="view-content">
	<?php
		$info = $this->data[0];
		$comments = $this->reviews[0];	
		$related_courses = $this->related;

		//recommend other courses to user
		echo "you may also want to see <br>";
		foreach ($related_courses as $key => $value) {
		echo "<a href='".$this->baseUrl()."/users/course/?course_id=".$key."'><p>".$value."</p></a>";
			echo "<br>";
		}			
	?>
	
<p>total enrolled : <?php echo $info['student_no']?> </p>
<p>duration : <?php echo $info['duration'] ?> </p>
<p>course description : <?php echo $info['course_desc'] ?>
<a href="<?php echo $this->baseUrl() ?>/users/startcourse/?course_id=<?php echo $info['id'] ?>&doc_no=1"><button>start course</button></a> 
<p>Reviews</p>
<?php

for($i=0;$i<count($this->reviews);$i++){
echo "<p>".$comments['comment']." /// ".$comments['username']."<p>";
}
?>
</div>
