<?php echo $this->headTitle("Search") ?>
<?php echo $this->layout()->content; ?>
<div class="row">
	<div class="col-md-3">
		<div class="container-fluid">

		
        <form action="<?php echo $this->baseUrl(); ?>/users/search" method="get" class="form-inline">
            
                <div class="form-group">
                    <div id="Skill">
                    <p>Skill Level:</p>
                    <select name="skill_level" class="form-control">
                      <?php if($this->courseData) 
                      {for($i=0; $i<count($this->courseData); $i++){?>

                      <option> <?php echo $this->courseData[$i]['skill_level']; ?> </option>
                      <?php } } ?>

                    </select>
                    </div>
                </div>
               </br> </br>    
                <div class="form-group">
                  <div id="language">
                      <p> Language: </p>
                      <select name="language" class="form-control">
                        <?php if($this->courseData) 
                        {for($i=0; $i<count($this->courseData); $i++){?>
                        <option> <?php echo $this->courseData[$i]['language']; ?> </option>
                          <?php } } ?>
                      </select>
                  </div>
                </div>
                </br> </br> 
                <div class="form-group">
                      <p>Category: </p>
                      <select name="category" class="form-control">
                        <?php if($this->search) 
                        {for($i=0; $i<count($this->catData); $i++){?>
                        <option> <?php echo $this->catData[$i]['category_name'] ?> </option>
                        <?php } } ?>
                      </select>
              </div>
              </br> </br> 
              <div class="form-group">
          <input type="submit" class="btn btn-info form-control" value="Search">
        </div>
     </form>
	  	</div>
	</div> 	
<!-- Show Data -->
<div class="container-fluid">
  <div class="col-md-9">
    <?php if($this->search) { 
      for($i=0; $i<count($this->search); $i++){
        ?>     
        <div class="col-md-4">
          <div class="thumbnail">
            <img alt="" src="<?php echo $this->baseUrl().'/images/1.jpg' ?>" alt="..." width="500px" heigth="300px" />
            <div class="caption">
              <h3>
                <?php echo $this->search[$i]['course_name']; ?>
              </h3>
              <p>
                <?php echo $this->search[$i]['course_desc']; ?>
              </p>
              <p>
                <a class="btn btn-primary" href="#">Action</a> <a class="btn" href="#">Action</a>
              </p>
            </div>
          </div>
        </div>
        <?php } } ?>
      <!-- </div> -->
     </div>  
    </div>
							<!-- Total Data -->

</div>

