<?php echo $this->headTitle("Search") ?>
<?php echo $this->layout()->content; ?>
<div class="row">
	<div class="col-md-3">
		<div class="container-fluid">

			 <!-- <form action="<?php //echo $this->baseUrl(); ?>/users/search">
			 	<h3> Skill Level: </h3>
				  <input type="checkbox" name="advance" value="Advanced">Advanced</br> 
				  <input type="checkbox" name="inter" value="Advanced">Intermediate</br>
				  <input type="checkbox" name="entry" value="Entry">Entry-Level</br>

				<h3> Language: </h3>
				  <input type="checkbox" name="english" value="English">English</br> 
				  <input type="checkbox" name="arabic" value="Arabic">Arabic</br>
				    
				<h3> Category: </h3>  
				  <input type="checkbox" name="category[]" value="Business">Business</br> 
				  <input type="checkbox" name="category[]" value="IT & Sodtware">IT & Sodtware</br>
				  <input type="checkbox" name="category[]" value="Development">Development</br>
				        
				  <input type="submit" value="Submit" name="submit"></br>
			   </form>  -->
        <form action="<?php echo $this->baseUrl(); ?>/users/search" method="get" class="form-inline">
            
            <div class="form-group">
                <div id="Skill">
                <p>Skill Level:</p>
                <select name="skill" class="form-control">
                  <?php if($this->courseData) 
                  {for($i=0; $i<count($this->courseData); $i++){?>

                  <option> <?php echo $this->courseData[$i]['skill_level']; ?> </option>
                    <!-- <option value="Advanced" name="Advanced">Advanced</option>
                    <option value="Intermediate" name="Intermediate">Intermediate</option>
                    <option value="Entry" name="Entry">Entry</option> -->
                  <?php } } ?>

                </select>
                </div>
            </div>
         </br> </br>    
          <div class="form-group">
            <div id="language">
                <p> Language: </p>
                <select name="language" class="form-control">
                  <?php if($this->courseData) 
                  {for($i=0; $i<count($this->courseData); $i++){?>
                  <option> <?php echo $this->courseData[$i]['language']; ?> </option>
                    <!-- <option value="English" name="English">English</option>
                    <option value="Arabic" name="Arabic">Arabic</option> -->
                    <?php } } ?>
                </select>
            </div>
          </div>
        </br> </br> 
          <div class="form-group">
            <div id="category">
                <p>Category: </p>
                <select name="category" class="form-control">
                  <?php if($this->search) 
                  {for($i=0; $i<count($this->catData); $i++){?>
                  <option> <?php echo $this->catData[$i]['category_name'] ?> </option>
                  <?php } } ?>
                    <!-- <option value="Business" name="Business" >Business</option>
                    <option value="IT & Sodtware" name="IT & Software" >IT & Software</option>
                    <option value="Development" name="Development" >Development</option> -->
                </select>
            </div>
        </div>
    </br> </br> 
        <div class="form-group">
            <input type="submit" class="btn btn-info form-control" value="Search">
        </div>
     </form>
	  	</div>
	</div> 	
<!-- Show Data -->
<div class="container-fluid">
  <div class="col-md-9">
    <?php if($this->search) { 
      for($i=0; $i<count($this->search); $i++){
        ?>     
        <div class="col-md-4">
          <div class="thumbnail">
            <img alt="" src="<?php echo $this->baseUrl().'/images/1.jpg' ?>" alt="..." width="500px" heigth="300px" />
            <div class="caption">
              <h3>
                <?php echo $this->search[$i]['course_name']; ?>
              </h3>
              <p>
                <?php echo $this->search[$i]['course_desc']; ?>
              </p>
              <p>
                <a class="btn btn-primary" href="#">Action</a> <a class="btn" href="#">Action</a>
              </p>
            </div>
          </div>
        </div>
        <?php } } ?>
      <!-- </div> -->
     </div>  
    </div>
							<!-- Total Data -->

</div>

