
<div class="row">
		<div class="col-md-3">

		</div>
		<div class="col-md-6">
			<?php

				echo "<table class='table'>";
				if(isset($this->userInfo)){
					// var_dump($this->userInfo);
					
					// echo "<form action='/users/update-image' method='post'>";
					echo "<tr>";
					echo "<td> <img src='/images/upload/". basename($this->userInfo->image)."'/></td>"; 
					echo "<td> </td>"  ;    
					echo "</tr>";

					echo "<tr>";
					// echo "<td><input type='file' value='Upload PHoto' class='btn btn-primary' name='image' /></td>";
					echo "<td class='success'>".$this->form."</td>"; 

					// echo "<td><input type='submit' value='Edit Photo' class='btn btn-primary' /></td>";
					echo "</tr>";
					// echo "</form>";
					/////////////////
					echo "<form action='/users/update-elem' method='post'>";
					echo "<tr>";
					
					echo "<td class='success'>  <input type='text' value='".$this->userInfo->name."' name='name' class='form-control'/></td>";
					
					
					echo "<td class='warning'><input type='submit' value='Edit Name' class='btn btn-primary'/></td>";
					
					
					echo "</tr>";
					echo "</form>";
///////////////////////////////////
					echo "<form action='/users/update-elem' method='post'>";
					echo "<tr>";
					echo "<td class='success'> <input type='text' value='".$this->userInfo->email."' name='email' class='form-control'/></td>";
					// echo "</tr>";

					// echo "<tr>";
					echo "<td class='warning'><input type='submit' value='Edit Email' class='btn btn-primary'/></td>";
					echo "</tr>";
					echo "</form>";
/////////////////////////////////////////
					echo "<form action='/users/update-elem' method='post'>";
					echo "<tr>";
					echo "<td class='success'>  <input type='password' value='".$this->userInfo->password."' name='password' class='form-control'/></td>";
					// echo "</tr>";

					// echo "<tr>";
					echo "<td class='warning'><input type='submit' value='Edit Password' class='btn btn-primary'/></td>";
					echo "</tr>";
					echo "</form>";
		/////////////////////////////////////////////////
					// echo "<form action='/users/update-elem' method='post'>";
					// echo "<tr>";
					// echo "<td class='success'>  <input type='text' value='".$this->userInfo->username."' name='username' class='form-control'/></td>";
					// // echo "</tr>";

					// // echo "<tr>";
					// echo "<td class='warning'><input type='submit' value='Edit User Name' class='btn btn-primary'/></td>";
					// echo "</tr>";
					// echo "</form>";
					
				}
				echo "</table>";
				// echo $this->form;
			?>


		</div>
		<div class="col-md-3">

		</div>
</div>