<?php

if(isset($this->userInfo)){
	var_dump($this->userInfo);

	echo "<h2> Name :".$this->userInfo->name."";
	echo "<h2> Email:".$this->userInfo->email."";
	echo "<h2> Password : ".$this->userInfo->password."";
	echo "<h2> image : ".$this->userInfo->image;
	// echo base64_decode($this->userInfo->image);
	var_dump($this->userInfo->image['content']);
}

echo $this->form;
?>

	<img id="pic_1" src="<?php echo $this->baseUrl($this->userInfo->image) ?>"/> 
