 <script type="text/javascript" src="jquery-1.11.2.js"></script>
<br /><br />
<div id="view-content">
	<?php
		//get data from controller
		$data_list = $this->listdata;
		$document = $this->document;
		
		//get list of course's documents
		for($i=0;$i<count($data_list);$i++){
		$doc = split('/',$data_list[$i]['material'],5);

		//get type of file
		$doc_type = split('\.',$doc[4],2);

		//each link map to new document
		?><a href="<?php echo $this->baseUrl() ?>/users/startcourse/?course_id='<?php echo $data_list[$i]['course_id']?>'&doc_no='<?php  echo $data_list[$i]['doc_no']?>'"><p><?php echo $doc[4] ?></p></a><?php
		}

	//get my public ip
	/*$curl_handle=curl_init();
	curl_setopt($curl_handle,CURLOPT_URL,'http://whatismyip.org/');
	curl_setopt($curl_handle,CURLOPT_RETURNTRANSFER,1);
	curl_setopt($curl_handle,CURLOPT_CONNECTTIMEOUT,2);
	$public_ip = curl_exec($curl_handle);
	curl_close($curl_handle);*/

	//check download option
	$locked = $document[0]['is_locked'];

	//check the type of file
	if($doc_type=='pdf'){
		//can't download
		if($locked!=0){
		?><iframe src="http://docs.google.com/gview?url=http://app<?php echo $document[0]['material'] ?>&embedded=true" 		style="width:600px; height:500px;" frameborder="0"></iframe> <?php
		}else{
			?><iframe src="<?php echo $document[0]['material']?>" width='600' height='380' style="border: none;"></iframe><?php
		}
	}else{
		//can't download
		if($locked!=0){?>
		 	<iframe src="<?php echo $document[0]['material'] ?>" width="600" height="380" style="border: none;"></iframe>
		<?php } else { ?>
			<a href="<?php echo $document[0]['material']?>" download><button>download</button></a>
			<iframe src="<?php echo $document[0]['material'] ?>" width="600" height="380" style="border: none;"></iframe>
		<?php }
	}
		?>
		<!-- add comment to material -->
		<input type="text" id="user_comment">
		<input type="hidden" id="course_id" value="<?php echo $document[0]['course_id'] ?>" />
		<button name="comment_btn" onclick="add_comment()">comment</button>

		<div id="comment_area"></div>

	
</div>
<script>
var add_comment = function(){
	var comment_text = $("#user_comment").val();
	var course_id = $("#course_id").val();

	if(comment_text!=""){
		$.ajax({
			url:'localhost/slms/public/users/addcomment',
			method:'get',
			data : {'com':comment_text,'course_id':course_id},
			success : function(res){
				$("#comment_area").append("<p>"+comment_text+"</p>");
			}
		});
	}
}
</script>
