
<?php echo $this->doctype() ?>
<html>
<head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<?php echo $this->headMeta(); ?>
<?php echo $this->headTitle() ?>
<?php echo $this->headLink() ?>

</head>
<body>
<!--FiXed Menu-->
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<nav class="navbar navbar-default" role="navigation">
				<div class="navbar-header">
					 
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						 <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
					</button> <a class="navbar-brand" href="#">Coursera</a>
				</div>
				
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li class="active">
							<a href="#">Catalog</a>
						</li>
					</ul>
					<form class="navbar-form navbar-left" role="search" onchange="showUser(this.value)">
						<div class="form-group">
							<input class="form-control" type="text" id="query" />
						</div> 
						<button type="submit" class="btn btn-default" id="search">
							Submit
						</button>
					</form>
					<ul class="nav navbar-nav navbar-right">
						<li>
							<a href="#">Login</a>
						</li>
					</ul>
					<ul class="nav navbar-nav navbar-right">
						<li>
							<a href="#">Sign Up</a>
						</li>
					</ul>
				</div>
				
			</nav>
		</div>
	</div>
</div>

<!--End Fixed Menu-->
<?php echo $this->layout()->content; ?>
<script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<script src="<?php echo $this->baseUrl().'/js/scripts.js'?>"></script>
<?php echo $this->headScript() ?>
</body>
</html>