
<?php echo $this->doctype(); ?>

<!DOCTYPE html>
<html>
<head>
<?php echo $this->headMeta(); ?>
<?php echo $this->headTitle() ?>
<?php echo $this->headLink() ?>
<?php echo $this->headScript() ?>


	<!-- <title>Blog</title>
	 <! Latest compiled and minified CSS -->
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>

	<!-- Latest compiled JavaScript -->
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<nav class="navbar navbar-default" role="navigation">
				<div class="navbar-header">
					 
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						 <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
					</button> <a class="navbar-brand" href="#">Coursera</a>
					</button> <a class="navbar-brand" href="/">Et3lm</a>
				</div>
				
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li class="active">
							<a href="#">Catalog</a>
						</li>
					</ul>
					<form class="navbar-form navbar-left" role="search" onchange="showUser(this.value)">
						<div class="form-group">
							<input class="form-control" type="text" id="query" />
						</div> 
						<button type="submit" class="btn btn-default" id="search">
							Submit
							<a href="/">Home</a>
						</li>
						
						<?php
							if(!Zend_Auth::getInstance()->hasIdentity()){
								echo "<li>";
								echo "<a href='/users/register'>Registration</a>";
								echo "</li>";

								echo "<li>";
								echo "<a href='/users/login'>Login</a>";
								echo "</li>";
							}

						?>
						
					</ul>
					<form class="navbar-form navbar-left" role="search">
						<div class="form-group">
							<input class="form-control" type="text" />
						</div> 
						<button type="submit" class="btn btn-default">
							Search
						</button>
					</form>
					<ul class="nav navbar-nav navbar-right">
						<li>
							<a href="#">Login</a>
						</li>
					</ul>
					<ul class="nav navbar-nav navbar-right">
						<li>
							<a href="#">Sign Up</a>
						</li>
							<a href="/about-us">About Us</a>
						</li>
						
						<li>
						<?php
							if(Zend_Auth::getInstance()->hasIdentity()){
								$userInfo = Zend_Auth::getInstance()->getStorage()->read();
                    			echo "Welcome <strong>".$userInfo->name."</strong>";
                    			echo "</li";
                    			echo "<li>";
                    			echo "<a href='/users/logout'>LogOut</a>";
                    			echo "</li>";
							}
						        				       
						 ?>
					</ul>
				</div>
				
			</nav>
		</div>
	</div>
</div>

<!--End Fixed Menu-->
<?php echo $this->layout()->content; ?>
<script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<script src="<?php echo $this->baseUrl().'/js/scripts.js'?>"></script>
<?php echo $this->headScript() ?>
</body>
</html>


	<div class="row">
	<div class="col-md-2">

	</div>
		<div class="col-md-6">

								
			<!-- <div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">
						Post Title
					</h3>
				</div>
				<div class="panel-body">
					Post content
				</div>
				<div class="panel-footer">
					Post footer
				</div>
			</div -->
			<?php echo $this->layout()->content; ?>
		</div>
		<div class="col-md-4">
			<!-- <?php //echo $this->layout()->content; ?> -->

		</div>
	</div>



	<div class="row">
		<div class="col-md-12">
			
			<div class="panel panel-default">
				<div class="panel-body">
					<strong >Open Source </strong>. <small><a>Khaled-Zahra-Sobhy</a></small>
				</div>
			</div>	
		</div>
	</div>
</div>




</body>
</html>
