<!-- <h1> Add Category </h1>
<br /><br />
<div class="row">
	<div class="col-md-12">
		<div class="container-fluid">
			
					<form action="/admin/addcategory" method="post">
			        	Category Name:<input type="text" name="category_name">
			        	<br> <br>
 						<input type="submit" value="Add" class="btn btn-info btn-md" required>
 						<br> <br>
 					</form>	

		</div>
	</div>
</div>	 -->


<?php echo $this->headTitle("Add Category") ?>
<?php echo $this->layout()->content; ?>

<?php if (isset($this->flag)) { ?>
<h1>Add Category </h1>
<?php } else { ?>
<h1> Edit Category </h1>
<?php }  ?>

<?php echo $this->form; ?>
<br>
<a type="button" class="btn btn-success btn-md" href="<?php echo $this->baseUrl()?>/admin/categories"> List Categories </a>

