<?php echo $this->headTitle("List Categories") ?>
<?php echo $this->layout()->content; ?>
<h1> List Categories </h1>
<br /><br />
<div class="row">
	<div class="col-md-12">
		<div class="container-fluid">
			<table class="table table-bordered">
				<thead>
					<th>ID</th>
					<th>Category</th>
					<th>Delete</th>
					<th>Edit</th>
				</thead>	
				<?php if($this->Data){for($i=0; $i<count($this->Data); $i++){?>
				<tr>
					<td name="id"> <?php echo $this->Data[$i]['id']; ?> </td>
					<td name="name"> <?php echo $this->Data[$i]['category_name']; ?> </td>
					<td>
						<?php echo '<a href="'.$this->baseUrl().'/admin/delete/id/'.$this->Data[$i]['id'].'"> Delete</a>'?>						
					</td>
					<td>
						<button type="button" class="btn btn-info btn-md" data-toggle="modal" data-target="#test">
							<?php echo '<a href="'.$this->baseUrl().'/admin/edit/id/'.$this->Data[$i]['id'].'"></a>'?> Edit
						</button>
					</td>	
						
<!-- '<button type="button" class="btn btn-info btn-md" data-toggle="modal" data-target="test">
 -->				
				</tr>
				<?php } } ?>
			</table>

						<!-- ================ADD Modal================= -->
			<div id="myModal" class="modal fade" role="dialog">
			  <div class="modal-dialog">

			    <!-- Modal content-->
			    <div class="modal-content">
			      <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal">&times;</button>
			        <h4 class="modal-title">Add Category</h4>
			      </div>
			      <div class="modal-body">
			        	Category Name:<input type="text" name="cat" id="addname"> 
			         </div>
			         <div class="modal-footer">
			         <button type="button" class="btn btn-info btn-md" id="addAj">Add</button>
			      	</div>
			        </form>	
			      </div>

			  	</div>
				</div>
			</div>

							<!-- =============Button ADD Modal=========== -->
					<td><button type="button" class="btn btn-info btn-md" data-toggle="modal" data-target="#myModal">Add</button>
					</td>

								<!-- ==========Edit Modal=========== -->
<!-- 		<div id="test" class="modal fade" role="dialog">
			  <div class="modal-dialog">

			    <!- Modal content-->
			   <!--  <div class="modal-content">
			      <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal">&times;</button>
			        <h4 class="modal-title">Edit Category</h4>
			      </div>
			      <div class="modal-body">
			        <form action="<?php //echo $this->baseUrl(); ?>/admin/categories>" method="put">
			        <?php //if($this->form){for($i=0; $i<count($this->form); $i++){?>

			        	Category ID:<input type="text" name="id" value=<?php //echo $this->form[$i]['id']; ?> > 
			        	Category Name:<input type="text" name="catName" value=<?php //echo $this->form[$i]['category_name']; ?> > 
			        <? //php } } ?>	
			         </div>
			         <div class="modal-footer">
			         <input type="submit" value="submit" class="btn btn-default" data-dismiss="modal">
			      	</div>
			      </form>	
			    </div>
			  </div>
			</div>
		</div> --> 

		</div>
	</div>
</div>	

